# Generated by Django 3.2 on 2021-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfs/'),
        ),
    ]
