# Generated by Django 3.2.2 on 2021-06-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webera', '0002_videomodel_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
