# Generated by Django 3.2.2 on 2021-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webera', '0004_videomodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='images',
            field=models.ImageField(default="{% static 'img/video.png'%}", upload_to='images/'),
        ),
    ]
