# Generated by Django 3.2.2 on 2021-06-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webera', '0006_alter_coursemodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='images',
            field=models.ImageField(default='video.png', upload_to='images/'),
        ),
    ]
