# Generated by Django 3.2.2 on 2021-06-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webera', '0007_auto_20210610_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='images',
            field=models.ImageField(default='media/images/video.png', upload_to='images/'),
        ),
    ]
