# Generated by Django 3.1.7 on 2021-06-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webera', '0010_alter_videomodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
