# Generated by Django 3.2.2 on 2021-06-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webera', '0013_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
